### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by VincentJoshuaET** [gusarov/InstagramAdKiller#1]
Same issue as the previous version of Twitter AdKiller APK.

_Sent from my Redmi Note 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gusarov** [comment]
Can you share the screenshot? People saying everything works.
If you still encountering this issue, I can suggest to do 
`adb uninstall ru.xkip.noad.instagram`
before installation. This is especially useful if you ever tried to install your build from the sources (with different signature).
